export type ErrorCode =
  | 'VALIDATION_ERROR'
  | 'PAIRING_CODE_INVALID'
  | 'UNAUTHORIZED'
  | 'DEVICE_TOKEN_INVALID'
  | 'FORBIDDEN'
  | 'DEVICE_LIMIT_PAYMENT_REQUIRED'
  | 'DEVICE_LIMIT_BLOCKED'
  | 'LAST_DEVICE_PROTECTED'
  | 'NAMESPACE_NOT_FOUND'
  | 'DEVICE_NOT_FOUND'
  | 'NAMESPACE_EXISTS'
  | 'DOCUMENT_NOT_FOUND'
  | 'NOT_FOUND'
  | 'INVALID_DOCUMENT_ID'
  | 'DOCUMENT_ID_NOT_ALLOWED'
  | 'DOCUMENT_LIMIT_REACHED'
  | 'ENVELOPE_DOCUMENT_MISMATCH'
  | 'REVISION_CONFLICT'
  | 'ENVELOPE_INVALID'
  | 'ENVELOPE_TOO_LARGE'
  | 'CONTENT_TYPE_NOT_ALLOWED'
  | 'RECOVERY_INVALID'
  | 'RATE_LIMIT_EXCEEDED'
  | 'UNLOCK_CODE_INVALID'
  | 'UNLOCK_CODE_ALREADY_REDEEMED'
  | 'ADMIN_API_DISABLED'
  | 'APP_ID_REQUIRED'
  | 'APP_ORIGIN_REQUIRED'
  | 'APP_NATIVE_ID_REQUIRED'
  | 'APP_CLIENT_SECRET_INVALID'
  | 'APP_NOT_FOUND'
  | 'APP_NOT_VERIFIED'
  | 'APP_SUSPENDED'
  | 'APP_ARCHIVED'
  | 'APP_ORIGIN_NOT_ALLOWED'
  | 'APP_BUNDLE_NOT_ALLOWED'
  | 'APP_NAMESPACE_MISMATCH'
  | 'APP_PAIRING_NOT_ALLOWED'
  | 'APP_ORIGIN_EXISTS'
  | 'APP_BUNDLE_EXISTS'
  | 'APP_ORIGIN_VERIFICATION_FAILED'
  | 'DEVELOPER_PORTAL_DISABLED'
  | 'DEVELOPER_EMAIL_EXISTS'
  | 'DEVELOPER_INVALID_CREDENTIALS'
  | 'DEVELOPER_EMAIL_NOT_VERIFIED'
  | 'DEVELOPER_ACCOUNT_DISABLED'
  | 'DEVELOPER_APP_LIMIT_REACHED'
  | 'DEVELOPER_FORBIDDEN'
  | 'INTERNAL_ERROR'

export class AppError extends Error {
  constructor(
    readonly statusCode: number,
    readonly code: ErrorCode,
    message: string,
    readonly details: Record<string, unknown> = {},
  ) {
    super(message)
    this.name = 'AppError'
  }
}

export function isAppError(error: unknown): error is AppError {
  return error instanceof AppError
}
